### ISSUE TITLE
访问首页页面为空白

### ISSUE THREAD

**Issue by ghost** [yeshm/mini-ofbiz#1]
**服务正常启动**

|I| Connector AJP/1.3 @ 8009 - not-secure [org.apache.coyote.ajp.AjpProtocol] started.
     [java] 2016-09-06 14:37:42,080 |main                 |CatalinaContainer             |I| Connector "http-bio-0.0.0.0-8080" @ 8080 - not-secure [org.apache.coyote.http11.Http11Protocol] started.
     [java] 2016-09-06 14:37:42,080 |main                 |CatalinaContainer             |I| Connector "http-bio-0.0.0.0-8443" @ 8443 - secure [org.apache.coyote.http11.Http11Protocol] started.
     [java] 2016-09-06 14:37:42,080 |main                 |CatalinaContainer             |I| Started Apache Tomcat/7.0.68
     [java] 2016-09-06 14:37:42,080 |main                 |ContainerLoader               |I| Started container catalina-container
     [java] Sep 06, 2016 2:37:42 PM org.apache.catalina.util.LifecycleBase start
     [java] INFO: The start() method was called on component [StandardEngine[default-server].StandardHost[0.0.0.0].StandardContext[/webtools]] after start() had already been called. The second call will be ignored.
     [java] 2016-09-06 14:37:42,352 |OFBiz-JobPoller      |JobManager                    |I| No crashed jobs to re-schedule
### CommonScreens.xml中                 label text="Hello world!"  已加。http://localhost:8080/helloworld 页面是空白。请问是哪里没有生效啊。

   <?xml version="1.0" encoding="UTF-8"?>
   <screens xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/widget-screen.xsd">
    <screen name="main-decorator">
        <section>
            <actions>
                <property-map resource="HelloWorldUiLabels" map-name="uiLabelMap" global="true"/>
                <property-map resource="CommonUiLabels" map-name="uiLabelMap" global="true"/>

```
            <set field="layoutSettings.companyName" from-field="uiLabelMap.HelloWorldCompanyName" global="true"/>
            <set field="layoutSettings.companySubtitle" from-field="uiLabelMap.HelloWorldCompanySubtitle" global="true"/>
            <label text="Hello world!"/>
            <set field="activeApp" value="helloworld" global="true"/>
            <set field="applicationMenuName" value="MainAppBar" global="true"/>
            <set field="applicationMenuLocation" value="component://helloworld/widget/HelloWorldMenus.xml" global="true"/>
            <set field="applicationTitle" value="${uiLabelMap.HelloWorldApplication}" global="true"/>
        </actions>
        <widgets>
            <include-screen name="GlobalDecorator" location="component://common/widget/CommonScreens.xml"/>
        </widgets>
    </section>
</screen>

<screen name="HelloWorldCommonDecorator">
    <section>
        <actions>
        </actions>
        <widgets>
            <decorator-screen name="main-decorator" location="${parameters.mainDecoratorLocation}">
                <decorator-section name="body">
                    <section>
                        <condition>
                            <if-has-permission permission="HELLOWORLD" action="_VIEW"/>
                        </condition>
                        <widgets>
                            <decorator-section-include name="body"/>
                        </widgets>
                        <fail-widgets>
                            <label style="h3">${uiLabelMap.HelloWorldViewPermissionError}</label>
                        </fail-widgets>
                    </section>
                </decorator-section>
            </decorator-screen>
        </widgets>
    </section>
</screen>
```

</screens>

**Comment by ghost** [comment]
http://localhost:8080/example/
可以

**Comment by yeshm** [comment]
是否创建helloworld component后没有重启？

**Comment by ghost** [comment]
OK 可以访问了。
